### ISSUE TITLE
메인 페이지에서 힌트메소드 호출 

### ISSUE THREAD

**Issue by syongsyong6035** [backendProjectGroup3/hangedManProject#9]
## 💡 요청 내용
여기서 힌트 메소드를 불러올때 매개변수가 필요한데 작성한 예시 메인 메소드 처럼 
난이도별로 가져온 메소드의 문자열과 현재까지 맞춘 문자열 ex) String st="ex_m_ _" 처럼 그리고 목숨수도 매개변수로 보내야함  
## 🔍 문제점 혹은 필요성
요청한 기능이나 개선이 필요한 부분에 대한 문제점이나 필요성을 적어주세요.

## 🚀 구현 방안
메인 페이지에서 힌트 메소드를 불러오면서  목숨 수, 정답 문자열 , 현재 맞춘 문자(빈칸 포함) 매개변수를
보내는 코드 작성함

## 🎉 예상 결과
hint 라고 메인 메소드에서 작성하면 힌트메소드로 이동하는 결과 발생함

**Comment by blackdemon129** [comment]
확인하였고 힌트 입력시 힌트 출력 부분을 간략히 구현해놓았습니다. 풀리퀘 했으니 확인하고 해결됐으면 이슈 클로즈 해주시면 됩니다!
